services:
  mongodb:
    image: mongo:5.0.25-focal
    restart: unless-stopped
    networks:
      - lila-network
    volumes:
      - ./repos/lila:/lila
      - ./scripts:/scripts

  redis:
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    networks:
      - lila-network

  lila:
    build:
      context: docker
      dockerfile: lila.Dockerfile
    restart: unless-stopped
    networks:
      - lila-network
    environment:
      - LILA_DOMAIN=${LILA_DOMAIN:-172.30.10.3:8080}
      - LILA_URL=${LILA_URL:-http://172.30.10.3:8080}
      - ENABLE_MONITORING=${ENABLE_MONITORING:-false}
    volumes:
      - ./repos/lila:/lila
      - ./repos/chessground:/chessground
      - ./repos/pgn-viewer:/pgn-viewer
      - ./repos/bbpPairings:/opt/bbpPairings
      - ./repos/scalachess:/scalachess
      - ./conf/lila.conf:/lila/conf/application.conf

  lila_ws:
    build:
      context: docker
      dockerfile: lila-ws.Dockerfile
    restart: unless-stopped
    networks:
      - lila-network
    environment:
      - LILA_URL=${LILA_URL:-http://172.30.10.3:8080}
      - ENABLE_MONITORING=${ENABLE_MONITORING:-false}
    volumes:
      - ./repos/lila-ws:/lila-ws
      - ./conf/lila-ws.conf:/lila-ws.conf

  nginx:
    image: nginx:1.25.4-alpine3.18-slim
    restart: unless-stopped
    networks:
      - lila-network
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./repos/lila/public:/lila/public
      - ./repos/lifat:/lifat
      - ./nginx:/nginx
    depends_on:
      - lila
      - lila_ws
  ui:
    build:
      context: docker
      dockerfile: ui.Dockerfile
    restart: unless-stopped
    networks:
      - lila-network
    volumes:
      - ./repos/lila:/lila
      - ./repos/chessground:/chessground
      - ./repos/pgn-viewer:/pgn-viewer
    profiles:
      - utils
  mongo_express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - lila-network
    depends_on:
      - mongodb

networks:
  lila-network:
    driver: bridge