services:
  mongodb:
    image: mongo:5.0.25-focal
    restart: unless-stopped
    networks:
      - lila-network
    volumes:
      - ./:/lila
    ports:
      - 27017:27017

  redis:
    image: redis:7.2.4-alpine3.19
    restart: unless-stopped
    networks:
      - lila-network
  
  mongo_express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - lila-network
    depends_on:
      - mongodb

networks:
  lila-network:
    driver: bridge